### ISSUE TITLE
Determine storage and user stories for parts list

### ISSUE THREAD

**Issue by vebyast** [to-boldly-go/tbg-shipdesigner#2]
Where is data stored for the parts list? How is data stored for the parts list? Who needs to be able to edit it and how?

**Comment by vebyast** [comment]
* Normal users need to be able to explore and propose balance changes, so storing everything in the git repository isn't feasible.
* It may be reasonable to store a canonical copy in the git repository but this introduces a single point of failure. Fallbacks should not just be possible but expected to see regular use, such as for testing balance changes.
* Format should be one that normal users can work with easily - even git is too much. Stick to CSV if possible. Even better if we can pull from a google spreadsheet. json may be workable.

**Comment by SV-AlphaDelta** [comment]
We should keep the parts and other editable configuration information in a separate repository. `tbg-shipdesigner-data`?

**Comment by vebyast** [comment]
Yeah, being able to version the canonical parts list separately from the app itself is a good idea. This is *if* we end up deciding to hold the canonical parts list ourselves - I'm still not decided on whether we require those changes to go through git or if we want Oneiros to be able to, for example, just declare a particular google spreadsheet to be The One Spreadsheet.

**Comment by vebyast** [comment]
ACTUALLY. We'll consume json, but we'll write a spreadsheet function on gdocs that exports a ship list to our json format! Best of both worlds.

**Comment by vebyast** [comment]
We have a workable solution for this now.
