### ISSUE TITLE
Future feature support for parts

### ISSUE THREAD

**Issue by vebyast** [to-boldly-go/tbg-shipdesigner#3]
Explicit support for multipliers on parts? A parts format that is inherently extensible (that is, nnnnot csv)? How to handle extensive existing one-off functionality?

**Comment by vebyast** [comment]
If I was writing a game for a desktop computer, I'd absolutely handle this the way kerbal space program or factorio do: Each part is a little bundle of assets and a bit of code that runs when the part is loaded so it can install itself into the engine - create a new object with the appropriate properties and callbacks and so on and so forth. The canon list of parts would be basically just the mod that ships with the game.

Of course this is completely infeasible for this project, since the parts list will regularly need to be tweaked by non-technical users and proposals will be handled by discussing in the forum thread instead of on pull requests with attached patches to code.

**Comment by vebyast** [comment]
I think that this might just end with every part having a column for every possible configuration option available. Not the best solution, but easy for non-technical users to handle.

**Comment by nixanten** [comment]
The effects a part can have in the sheet version: 

* Add to stats and costs
* Act as multiplier to the effect and/or cost of another part (subframes, burst launcher, phaser arrays)
* Restrict parts of another category to a specific subtype (engineering subframe for nav deflector)
* Set/restrict quantity of another part (hull for SIF, warp core for EPS, injectors, cooling)
* Add a situational stat bonus (survey sensors for mapping missions)

Most of these can currently be represented by rules for part types and subtypes.

**Comment by SV-AlphaDelta** [comment]
JSON or YAML may be a better option, as comma separated values aren't the most readable. On the other hand, as long as we provide an UI, the data's format is irrelevant. However, that's another separate set of problems.

**Comment by vebyast** [comment]
If we prioritize the editing tool, I would *strongly* prefer using json. It's easier to work with and more extensible in nearly every way. I'm only really considering the csv feature so that people can continue working with the parts lists in spreadsheets.

**Comment by SV-AlphaDelta** [comment]
Ah. Well, we could produce a conversion tool, though that's probably outside the scope of what v1.0 should be - replicating existing features.

**Comment by vebyast** [comment]
The very first conversion can be done by hand as part of the work on this project. It's maintenance that I'm worried about, and that can be handled by users given a part editor.

**Comment by DicePriestess** [comment]
Could we not make the app pull from a database that people can just download at leisure from here?

For example:
We unlock new parts.
Someone adds the new parts + their stats to the DB.
Everyone who wants to make a ship tosses the old version, or overwrites the old with the new. End result: version updated, with all the new parts.

**Comment by SV-AlphaDelta** [comment]
> Could we not make the app pull from a database that people can just download at leisure from here?

See: #2 

We will have a separate repository for data. That way, we can make changes to the canonical parts without modifying the app itself. Besides, all of the cool projects are setup this way. 

We will have to add support for configuration editing anyways, so we might as well design the application accordingly.

**Comment by DicePriestess** [comment]
I didn't see that, thanks.

**Comment by vebyast** [comment]
The big issue with keeping things in a git repository is that the whole github version control cycle - download tools, learn to command line, clone, modify, pull, push, make pull request - is way too much for most people to handle. This is particularly an issue because SWB is nontechnical and may have trouble with anything that lives in a git repository. This is also why I'd require a parts editor if we wanted to use json; json is *not at all* friendly to hand-editing by nontechnical users.

**Comment by DicePriestess** [comment]
I'm not sure I follow.

When I say "database" I just mean "spreadsheet with what we need on it". I think most folks can use Excel to the extent of being able to add values and names in the appropriate places.

This may be just a communications malfunction, though. I'm so new to this the plastic wrapping still isn't completely off my box.

**Comment by SV-AlphaDelta** [comment]
SWB should be able to use the Github Desktop client though.

Alternatively, he can just post it for a data maintainer to update.

**Comment by vebyast** [comment]
I think that the partbuilder completes this. It's not perfect, things like rapidshare and google drive aren't _great_ for distributing parts lists, but they work.
