### ISSUE TITLE
Year of Subframe Part

### ISSUE THREAD

**Issue by synchronizedwritersblock** [to-boldly-go/tbg-shipdesigner#39]
In the ship designer, the year of subframe parts is displayed as the maximum year of the other parts in that subframe.

While this is not outright incorrect as a summary of other information, it is misleading as each subframe itself has a year of research. I would request that the subframe's year of research be displayed instead.

**Comment by lbmaian** [comment]
Welp, turns out that the subframe's year of availability is also being ignored in the complete design's year of availability. So this is also a bug.

**Comment by lbmaian** [comment]
Addressed by c5376c790d8a19a9774be5084c7120427e62df0c
