### ISSUE TITLE
Creating a UI

### ISSUE THREAD

**Issue by DicePriestess** [to-boldly-go/tbg-shipdesigner#5]
We're also going to need a mildly decent UI. Nothing fancy. Aurora-style works. But it's got to be usable, else the app is pointless.

**Comment by vebyast** [comment]
I think that we'll have to stick with text, yes.

Whoever does the UI will need to figure out a good way to represent:
* Validation errors (too many of this, too little of that, numbers here too high, numbers here too low)
* Noteworthy values (militarization points, dangerous values)
* Permitted parts for particular slots (comboboxes eeeeeverywhere) and how those change in response to other configurations

We'll want some design work done. I'd like this to be at least a *little* bit pretty, so at least some colors or something?

**Comment by vebyast** [comment]
The most important thing is a layout: We need to know where things are, how the user moves between different parts of the app, making sure the app fits on common screen sizes, making sure that important information easy to find/notice without being distracting.

**Comment by SV-AlphaDelta** [comment]
I believe the current goal for v1.0 is a static page that can be hosted on Github pages. Thus, everything must be clientside JS. 

Ideally, we would completely abstract the display components from the internal engine.

**Comment by vebyast** [comment]
I'm planning to use (vue)[https://vuejs.org/] to make the UI work easier on myself.

Speaking of separation, I do intend to keep the ship-design engine code completely separate from the presentation logic. Almost necessarily as a part of good software design, in fact; I intend to go about this project in a somewhat test-driven manner. I also want to enforce that separation for more nefarious purposes, specifically, hooking the engine up to a general optimization tool and beating SWB using math.

**Comment by vebyast** [comment]
UI functional. :D
