### ISSUE TITLE
Reimplement Formulas and Parts

### ISSUE THREAD

**Issue by SV-AlphaDelta** [to-boldly-go/tbg-shipdesigner#6]
This needs to be finished before any UI work or other improvements can be done.

**Comment by vebyast** [comment]
This can actually happen a bit later on. See #7 for architectural thoughts that will allow this. Generally, we hammer out an API contract, including the shapes of the data structures we'll be passing around, and then we can each implement our own parts independently by using hand-crafted example data. For example, the bit of the user interface for presenting statlines can be built with only a statline on hand, hand-crafted or even hardcoded during the development process. Then it can be used in the full application using statlines that come from the ship engine.

**Comment by vebyast** [comment]
MVP of this done. May end up being the final version, it's a bit ugly.
