### ISSUE TITLE
Parts Editor: Stats selected but unchanged are set to 0 even if they have an existing value

### ISSUE THREAD

**Issue by synchronizedwritersblock** [to-boldly-go/tbg-shipdesigner#67]
In the Parts Editor if a stat is selected, but has not been changed, and then is deselected in some way, it is set to 0.

This is especially an issue because a common use-case is to use tab to fill out a part's stats, which will mean that tabbing through stats you don't want to change will set them to 0. It also happens when you do something like "Save current parts" after having edited a part but forgotten to hit enter or click outside.

I _believe_ this only happens for certain fields, the part name or year is not set to 0, may be numbers only?

**Comment by lbmaian** [comment]
This is a regression from 370c1e9f7060a3545bb0bf5b76d25d4bad8878d8 - fix coming up.
