### ISSUE TITLE
Add ability to reorder parts in parts list editor

### ISSUE THREAD

**Issue by lbmaian** [to-boldly-go/tbg-shipdesigner#74]
Currently, the only way to change the order of parts list in the editor is to sort them, but that's a view-only temporary sort that doesn't affect the underlying parts list data, the sort is unstable and thus precludes secondary sorting, and the oftentimes the user just wants to reorder a single or couple parts rather than the whole list. We should add a way to manually reorder (via drag & drop?) parts. And/or allow permanent resorts?

**Comment by OnAGravitasHunt** [comment]
I'm using [Vue.Draggable](https://github.com/SortableJS/Vue.Draggable) in my project. I'm probably also going to work it into my data lists (the Edit button) which I based on the part editor list.

**Comment by lbmaian** [comment]
Implemented and deployed!
